spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 1000
            read-timeout: 2000
            logger-level: full
          service-product:
            connect-timeout: 3000
            read-timeout: 5000
            logger-level: full
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8080

feign:
  sentinel:
    enabled: true