server:
  port: 8000

spring:
  application:
    name: service-order
  profiles:
    active: dev
    include: feign
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
        namespace: ${spring.profiles.active:public}

logging:
  level:
    com.atguigu.order.feign: debug


